// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp5-byqS8kFhujH1Kc8O5YL7SO3CxaxjY',
    appId: '1:1019400989277:web:d77b97afb66909031bfbb4',
    messagingSenderId: '1019400989277',
    projectId: 'eos-clock-931c3',
    authDomain: 'eos-clock-931c3.firebaseapp.com',
    storageBucket: 'eos-clock-931c3.appspot.com',
    measurementId: 'G-SXQERS0R8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConZ_K1hlnU7fp9-HA6dM9e_RcbasP1Ss',
    appId: '1:1019400989277:android:46a2e08f18a07dac1bfbb4',
    messagingSenderId: '1019400989277',
    projectId: 'eos-clock-931c3',
    storageBucket: 'eos-clock-931c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5bEHJdNg3erEgksFh0QXumqh5rT9NXk',
    appId: '1:1019400989277:ios:ccfed63f07e2d9e31bfbb4',
    messagingSenderId: '1019400989277',
    projectId: 'eos-clock-931c3',
    storageBucket: 'eos-clock-931c3.appspot.com',
    iosClientId: '1019400989277-g1v2krog6ung53kgfcjra5gvv1f0lq7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl5bEHJdNg3erEgksFh0QXumqh5rT9NXk',
    appId: '1:1019400989277:ios:3a7af155f809ffb51bfbb4',
    messagingSenderId: '1019400989277',
    projectId: 'eos-clock-931c3',
    storageBucket: 'eos-clock-931c3.appspot.com',
    iosClientId: '1019400989277-b07fgu01i7317kdeg1iu4bgkm7g454kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosClock.RunnerTests',
  );
}
